---
all:
  vars:
    ansible_user: devops
    ansible_port: 22
  children:
    platform:
      children:
        webservers: {}
        loadbalancers: {}
    validation:
      children:
        smoke: {}
    webservers:
      hosts:
        web_blue:
          ansible_host: servera.lab.example.com
        web_green:
          ansible_host: serverb.lab.example.com
    loadbalancers:
      hosts:
        load_balancer:
          ansible_host: serverc.lab.example.com
