---
namespace: exam
name: utilities
version: 0.0.0  # TODO
readme: README.md
authors:
  - EX374 Candidate
description: Mock exam utility collection
license:
  - GPL-2.0-or-later
tags: [exam, utilities]
dependencies: {}
